
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team02-s26-10
owner: ucsb-cs156-s26
repo_name: team02-s26-10
pull_requests: [{"author":{"id":"U_kgDOC5aqZA","is_bot":false,"login":"omkulkarni77","name":""},"headRefName":"ok-12","number":76,"title":"Create ucsbOrganizationFixtures.js","url":"https://github.com/ucsb-cs156-s26/team02-s26-10/pull/76"},{"author":{"id":"U_kgDOCyT_AA","is_bot":false,"login":"alyoon04","name":""},"headRefName":"alex/copy-backend-ucsbdiningcommonsmenuitem","number":75,"title":"UCSBDiningCommonsMenuItem backend from team01","url":"https://github.com/ucsb-cs156-s26/team02-s26-10/pull/75"},{"author":{"id":"U_kgDOCxyfpw","is_bot":false,"login":"AmitKarthikeyan","name":"Amit Karthikeyan"},"headRefName":"AK_51","number":74,"title":"Copy Placeholders for Articles pages; add to App.js/AppNavbar.js","url":"https://github.com/ucsb-cs156-s26/team02-s26-10/pull/74"},{"author":{"id":"U_kgDOC5aqZA","is_bot":false,"login":"omkulkarni77","name":""},"headRefName":"ok-11","number":73,"title":"Copy UCSBOrganization backend files from team01 (closes #11)","url":"https://github.com/ucsb-cs156-s26/team02-s26-10/pull/73"},{"author":{"id":"MDQ6VXNlcjcyMTcxNTQ2","is_bot":false,"login":"Kazu-Pang","name":"Kazu Pang"},"headRefName":"KP-33","number":72,"title":"kp - placeholders for menuitemreview pages","url":"https://github.com/ucsb-cs156-s26/team02-s26-10/pull/72"},{"author":{"id":"U_kgDOCxyfpw","is_bot":false,"login":"AmitKarthikeyan","name":"Amit Karthikeyan"},"headRefName":"AK_50","number":71,"title":"Table Component for Articles plus tests","url":"https://github.com/ucsb-cs156-s26/team02-s26-10/pull/71"},{"author":{"id":"U_kgDOCxyfpw","is_bot":false,"login":"AmitKarthikeyan","name":"Amit Karthikeyan"},"headRefName":"AK_49","number":70,"title":"Form Component for Articles plus tests","url":"https://github.com/ucsb-cs156-s26/team02-s26-10/pull/70"},{"author":{"id":"U_kgDOCuipLw","is_bot":false,"login":"yuhangj554","name":"Yuhang Jiang"},"headRefName":"yj-40","number":69,"title":"yj - add Form Components","url":"https://github.com/ucsb-cs156-s26/team02-s26-10/pull/69"},{"author":{"id":"MDQ6VXNlcjcyMTcxNTQ2","is_bot":false,"login":"Kazu-Pang","name":"Kazu Pang"},"headRefName":"KP-32","number":68,"title":"kp - menuitemreview table and tests","url":"https://github.com/ucsb-cs156-s26/team02-s26-10/pull/68"},{"author":{"id":"U_kgDOCuipLw","is_bot":false,"login":"yuhangj554","name":"Yuhang Jiang"},"headRefName":"yj-39","number":67,"title":"yj - add fixture file for HelpRequest","url":"https://github.com/ucsb-cs156-s26/team02-s26-10/pull/67"}]
