
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team02-s26-10
owner: ucsb-cs156-s26
repo_name: team02-s26-10
pull_requests: [{"author":{"id":"U_kgDOC5aqZA","is_bot":false,"login":"omkulkarni77","name":""},"headRefName":"ok-17","number":110,"title":"Implement UCSBOrganizationIndexPage with tests and stories","url":"https://github.com/ucsb-cs156-s26/team02-s26-10/pull/110"},{"author":{"id":"U_kgDOCuipLw","is_bot":false,"login":"yuhangj554","name":"Yuhang Jiang"},"headRefName":"yj-45","number":102,"title":"yj - create edit page for help request","url":"https://github.com/ucsb-cs156-s26/team02-s26-10/pull/102"},{"author":{"id":"U_kgDOCuipLw","is_bot":false,"login":"yuhangj554","name":"Yuhang Jiang"},"headRefName":"yj-44","number":99,"title":"yj - created index page for HelpRequest","url":"https://github.com/ucsb-cs156-s26/team02-s26-10/pull/99"}]
